function Animation(e){this.getThis=function(){return this},this.update=function(){},this.render=function(){}}function Player(e){this.getThis=function(){return this},this.update=function(){},this.render=function(){}}function Level(e){this.getThis=function(){return this},this.update=function(){},this.render=function(){}}function Background(e,t,n,i,o,a){var h=e,s=t,r=n,c=i,d=o,g=a,u=0,l=0,f=parseFloat((width/(c*ScreenRatio)).toFixed(1))+1,m=1
this.getThis=function(){return this},this.update=function(e){u=parseFloat((u-e*g).toFixed(1))%(c*ScreenRatio)},this.render=function(e){var t=u>0?-1:0,n=l>0?-1:0
for(row=0;row<m;row++)for(col=0;col<f;col++)e.drawImage(h,s,r,c,d,u+(col+t)*c*ScreenRatio,l+(n+row)*d*ScreenRatio,c*ScreenRatio,d*ScreenRatio)}}function InputManager(){function e(e,t){return e>0&&e<width&&t>height-gameheight&&t<height-gameheight/2?!0:!1}function t(e,t){return e>.25*width&&e<.75*width&&t>height-gameheight/2&&t<height?!0:!1}function n(e,t){return e>0&&e<.25*width&&t>height-gameheight/2&&t<height?!0:!1}function i(e,t){return e>.75*width&&e<width&&t>height-gameheight/2&&t<height?!0:!1}var o=0,a=-1,h=-1,s=-1,r=-1
this.GetInput=function(){return o},this.handleKeyDown=function(e){var t=e.keyCode?e.keyCode:e.charCode
38===t&&(e.preventDefault(),o|=8),32===t&&(e.preventDefault(),o|=4),37===t&&(e.preventDefault(),o|=2),39===t&&(e.preventDefault(),o|=1)},this.handleKeyUp=function(e){var t=e.keyCode?e.keyCode:e.charCode
38===t&&(e.preventDefault(),o&=7),32===t&&(e.preventDefault(),o&=11),37===t&&(e.preventDefault(),o&=13),39===t&&(e.preventDefault(),o&=14)},this.handleStart=function(c){c.preventDefault(),DebugMode&&console.log("input : "+width+"-"+c.changedTouches[0].clientX+"-"+c.changedTouches[0].clientY)
var d=c.changedTouches[0].clientX-offsetX,g=c.changedTouches[0].clientY-offsetY
DebugMode&&console.log("input : "+width+"-"+d+"-"+g),e(d,g)&&(o|=8,a=c.changedTouches[0].identifier),t(d,g)&&(o|=4,r=c.changedTouches[0].identifier),n(d,g)&&(o|=2,h=c.changedTouches[0].identifier),i(d,g)&&(o|=1,s=c.changedTouches[0].identifier)},this.handleEnd=function(e){e.preventDefault(),a===e.changedTouches[0].identifier&&(o&=7),r===e.changedTouches[0].identifier&&(o&=11),h===e.changedTouches[0].identifier&&(o&=13),s===e.changedTouches[0].identifier&&(o&=14)}}function AssetManager(){function e(e,t,i,a){DebugMode&&console.log("PreLoad IMAGE : "+e),o[e]=new Image,o[e].name=e,o[e].frameWidth=i,o[e].frameHeight=a,o[e].onload=n,o[e].src=t}function t(e,t,i){DebugMode&&console.log("PreLoad SOUND : "+e),a[e]=new Audio,a[e].name=e,a[e].volume=i,a[e].addEventListener("canplaythrough",n,!1),a[e].src=t}function n(){s++,s===h&&(DebugMode&&console.log("AssetsLoaded"),i.start())}var i=0,o={}
this.imgs=o
var a={}
this.sounds=a
var h=0,s=0
this.PreLoad=function(n){i=n,DebugMode&&console.log("enter PreLoad"),h=5,s=0,e("bgs","assets/imgs/bgs.png",800,1800),e("ship","assets/imgs/ship.png",0,0),e("spritesheet","assets/imgs/spritesheet.png",20,20),t("laser","assets/sounds/laser.wav",.5),t("gameover","assets/sounds/background.mp3",.1),DebugMode&&console.log("exit PreLoad")}}function WorldRenderer(e){var t=e,n=[]
n[0]=new Background(t.imgs.bgs,0,0,800,600,0),n[1]=new Background(t.imgs.bgs,0,600,800,600,.5),n[2]=new Background(t.imgs.bgs,0,1200,800,600,1)
var o=(new Level(t),!1),a=!1,h=!1,s=!1
TestXpos=0,this.update=function(e){for(o=!1,a=!1,h=!1,s=!1,8===(8&e)&&(h=!0),4===(4&e)&&(s=!0),2===(2&e)&&(o=!0,TestXpos-=1,TestXpos<-10&&(TestXpos=-10)),1===(1&e)&&(a=!0,TestXpos+=1,TestXpos>10&&(TestXpos=10)),i=0;i<n.length;i++)n[i].update(TestXpos)
DebugMode&&console.log("TestXpos : "+TestXpos)},this.render=function(){for(ctx.clearRect(0,0,width,height),i=0;i<n.length;i++)n[i].render(ctx)
ctx.fillStyle="red",ctx.strokeStyle="red",ctx.rect(0,height-gameheight,width,height-gameheight),ctx.stroke(),!0===h&&ctx.fillRect(0,height-gameheight,width,gameheight/2),!0===s&&ctx.fillRect(.25*width,height-gameheight/2,width/2,gameheight/2),!0===o&&ctx.fillRect(0,height-gameheight/2,width/4,gameheight/2),!0===a&&ctx.fillRect(.75*width,height-gameheight/2,width/4,gameheight/2),ctx.fillStyle="white",ctx.font="15px Arial",ctx.fillText("Press or touch",.45*width,.45*gameheight),!0===h&&ctx.fillText("JUMP",.45*width,.25*gameheight),!0===s&&ctx.fillText("ACTION",.45*width,.75*gameheight),!0===o&&ctx.fillText("LEFT",.1*width,.75*gameheight),!0===a&&ctx.fillText("RIGHT",.8*width,.75*gameheight),!0===s&&t.sounds.laser.play()}}function Game(){var e,t=this
canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d"),width=canvas.width,height=canvas.height,gameheight=canvas.height,offsetX=0,offsetY=0,ScreenRatio=1
var n,i=60,o=(parseFloat((1/i).toFixed(1)),new AssetManager),a=new InputManager,h=(new Date).getTime(),s=0
t.init=function(){DebugMode&&console.log("enter init"),t.resize(),o.PreLoad(t)},t.start=function(){DebugMode&&console.log("enter start"),n=new WorldRenderer(o),o.sounds.gameover.currentTime=0,o.sounds.gameover.loop=!0,o.sounds.gameover.play(),DebugMode&&console.log("enter animate"),t.animate()},t.animate=function(){window.requestAnimFrame(t.animate),e=a.GetInput(),n.update(e),n.render(),s++
var i=(new Date).getTime(),o=(i-h)/1e3
Math.floor(s/o)
o>1&&(h=(new Date).getTime(),DebugMode&&console.log("FPS : "+s),s=0)},t.resize=function(){for(DebugMode&&console.log("enter resize"),offsetX=0,offsetY=0,element=canvas;element;)offsetX+=element.offsetLeft,offsetY+=element.offsetTop,element=element.offsetParent
ctx.canvas.width=ctx.canvas.offsetWidth,ctx.canvas.height=ctx.canvas.offsetHeight,width=ctx.canvas.width,height=ctx.canvas.height,gameheight=ctx.canvas.height,width<height&&(gameheight=parseFloat((height/2).toFixed(1))),ScreenRatio=parseFloat((gameheight/600).toFixed(1)),DebugMode&&console.log("ratio : "+ScreenRatio)},window.addEventListener("resize",t.resize,!1),window.addEventListener("orientationchange",t.resize,!1),document.addEventListener("keydown",a.handleKeyDown,!1),document.addEventListener("keyup",a.handleKeyUp,!1),canvas.addEventListener("touchstart",a.handleStart,!1),canvas.addEventListener("touchend",a.handleEnd,!1),canvas.addEventListener("touchleave",a.handleEnd,!1),t.init()}DebugMode=!1,window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(e){window.setTimeout(e,1e3/60)}}(),game=new Game
