function CustomSound(e,t,n){var i=e,o=null,n=n+"?nocache="+Math.random(),a=!1,s=new XMLHttpRequest,h=!0
this.setloop=function(e){a=e},this.request=function(){s.open("GET",n,!0),s.responseType="arraybuffer",s.onload=function(){Soundcontext.decodeAudioData(s.response,function(e){DebugMode&&console.log("buffer: "+e),o=e},null),i()},s.setRequestHeader("Cache-Control","no-cache"),s.send()},this.play=function(){if(!0===h&&null!=o){var e=Soundcontext.createBufferSource()
e.loop=a,e.buffer=o,e.connect(Soundcontext.destination),h=!1,e.start(0),e.onended=function(){h=!0,console.log("Your audio has finished playing")}}}}function Animation(e){this.getThis=function(){return this},this.update=function(){},this.render=function(){}}function Player(e){this.getThis=function(){return this},this.update=function(){},this.render=function(){}}function Level(e){this.getThis=function(){return this},this.update=function(){},this.render=function(){}}function Background(e,t,n,i,o,a){var s=e,h=t,d=n,r=i,c=o,u=a,g=0,l=0,f=parseFloat((width/(r*ScreenRatio)).toFixed(1))+1,w=1
this.getThis=function(){return this},this.update=function(e){g=parseFloat((g-e*u).toFixed(1))%(r*ScreenRatio)},this.render=function(e){var t=g>0?-1:0,n=l>0?-1:0
for(row=0;row<w;row++)for(col=0;col<f;col++)e.drawImage(s,h,d,r,c,g+(col+t)*r*ScreenRatio,l+(n+row)*c*ScreenRatio,r*ScreenRatio,c*ScreenRatio)}}function InputManager(){function e(e,t){return e>0&&e<width&&t>height-gameheight&&t<height-gameheight/2?!0:!1}function t(e,t){return e>.25*width&&e<.75*width&&t>height-gameheight/2&&t<height?!0:!1}function n(e,t){return e>0&&e<.25*width&&t>height-gameheight/2&&t<height?!0:!1}function i(e,t){return e>.75*width&&e<width&&t>height-gameheight/2&&t<height?!0:!1}var o=0,a=-1,s=-1,h=-1,d=-1
this.GetInput=function(){return o},this.handleKeyDown=function(e){var t=e.keyCode?e.keyCode:e.charCode
38===t&&(e.preventDefault(),o|=8),32===t&&(e.preventDefault(),o|=4),37===t&&(e.preventDefault(),o|=2),39===t&&(e.preventDefault(),o|=1)},this.handleKeyUp=function(e){var t=e.keyCode?e.keyCode:e.charCode
38===t&&(e.preventDefault(),o&=7),32===t&&(e.preventDefault(),o&=11),37===t&&(e.preventDefault(),o&=13),39===t&&(e.preventDefault(),o&=14)},this.handleStart=function(r){r.preventDefault(),DebugMode&&console.log("input : "+width+"-"+r.changedTouches[0].clientX+"-"+r.changedTouches[0].clientY)
var c=r.changedTouches[0].clientX-offsetX,u=r.changedTouches[0].clientY-offsetY
DebugMode&&console.log("input : "+width+"-"+c+"-"+u),e(c,u)&&(o|=8,a=r.changedTouches[0].identifier),t(c,u)&&(o|=4,d=r.changedTouches[0].identifier),n(c,u)&&(o|=2,s=r.changedTouches[0].identifier),i(c,u)&&(o|=1,h=r.changedTouches[0].identifier)},this.handleEnd=function(e){e.preventDefault(),a===e.changedTouches[0].identifier&&(o&=7),d===e.changedTouches[0].identifier&&(o&=11),s===e.changedTouches[0].identifier&&(o&=13),h===e.changedTouches[0].identifier&&(o&=14)}}function AssetManager(){function e(e,t,n,a){DebugMode&&console.log("PreLoad IMAGE : "+e),o[e]=new Image,o[e].name=e,o[e].frameWidth=n,o[e].frameHeight=a,o[e].onload=i.AssetLoaded,o[e].src=t}function t(e,t,n){DebugMode&&console.log("PreLoad SOUND : "+e),a[e]=new CustomSound(i.AssetLoaded,e,t,n),!0===soundEnabled&&a[e].request()}var n=0,i=this,o={}
this.imgs=o
var a={}
this.sounds=a
var s=0,h=0,d=0,r=0
this.PreLoad=function(i){n=i,DebugMode&&console.log("enter PreLoad"),s=3,h=2,d=!0===soundEnabled?s+h:s,r=0,e("bgs","assets/imgs/bgs.png",800,1800),e("ship","assets/imgs/ship.png",0,0),e("spritesheet","assets/imgs/spritesheet.png",20,20),t("laser","assets/sounds/laser.wav",.5),t("background","assets/sounds/background.mp3",.1),DebugMode&&console.log("exit PreLoad")},i.AssetLoaded=function(){r++,r===d&&(DebugMode&&console.log("AssetsLoaded"),n.start())}}function WorldRenderer(e){var t=e,n=[]
n[0]=new Background(t.imgs.bgs,0,0,800,600,0),n[1]=new Background(t.imgs.bgs,0,600,800,600,.5),n[2]=new Background(t.imgs.bgs,0,1200,800,600,1)
var o=(new Level(t),!1),a=!1,s=!1,h=!1
TestXpos=0,this.update=function(e){for(o=!1,a=!1,s=!1,h=!1,8===(8&e)&&(s=!0),4===(4&e)&&(h=!0),2===(2&e)&&(o=!0,TestXpos-=1,TestXpos<-10&&(TestXpos=-10)),1===(1&e)&&(a=!0,TestXpos+=1,TestXpos>10&&(TestXpos=10)),i=0;i<n.length;i++)n[i].update(TestXpos)},this.render=function(){for(ctx.clearRect(0,0,width,height),i=0;i<n.length;i++)n[i].render(ctx)
ctx.fillStyle="red",ctx.strokeStyle="red",ctx.rect(0,height-gameheight,width,height-gameheight),ctx.stroke(),!0===s&&ctx.fillRect(0,height-gameheight,width,gameheight/2),!0===h&&ctx.fillRect(.25*width,height-gameheight/2,width/2,gameheight/2),!0===o&&ctx.fillRect(0,height-gameheight/2,width/4,gameheight/2),!0===a&&ctx.fillRect(.75*width,height-gameheight/2,width/4,gameheight/2),ctx.fillStyle="white",ctx.font="15px Arial",ctx.fillText("Press or touch",.45*width,.45*gameheight),!0===s&&ctx.fillText("JUMP",.45*width,.25*gameheight),!0===h&&ctx.fillText("ACTION",.45*width,.75*gameheight),!0===o&&ctx.fillText("LEFT",.1*width,.75*gameheight),!0===a&&ctx.fillText("RIGHT",.8*width,.75*gameheight),!0===h&&t.sounds.laser.play()}}function Game(){function e(e){e.style.display="none"}function t(e){e.style.display="block"}function n(){e(canvas),t(a)}var i,o=this,a=document.getElementById("menu-wrapper"),s=!1
canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d"),width=canvas.width,height=canvas.height,gameheight=canvas.height,offsetX=0,offsetY=0,ScreenRatio=1,soundEnabled=!1
try{window.AudioContext=window.AudioContext||window.webkitAudioContext,Soundcontext=new AudioContext,soundEnabled=!0}catch(h){soundEnabled=!1,alert("Web Audio API is not supported in this browser")}var d,r=60,c=(parseFloat((1/r).toFixed(1)),new AssetManager),u=new InputManager;(new Date).getTime()
o.init=function(){DebugMode&&console.log("enter init"),o.resize(),c.PreLoad(o)},o.start=function(){DebugMode&&console.log("enter start"),d=new WorldRenderer(c),n(),DebugMode&&console.log("enter animate"),o.animate()},o.animate=function(){window.requestAnimFrame(o.animate),!0===s&&(i=u.GetInput(),d.update(i)),d.render()},o.resize=function(){for(DebugMode&&console.log("enter resize"),offsetX=0,offsetY=0,element=canvas;element;)offsetX+=element.offsetLeft,offsetY+=element.offsetTop,element=element.offsetParent
ctx.canvas.width=ctx.canvas.offsetWidth,ctx.canvas.height=ctx.canvas.offsetHeight,width=ctx.canvas.width,height=ctx.canvas.height,gameheight=ctx.canvas.height,width<height&&(gameheight=parseFloat((height/2).toFixed(1))),ScreenRatio=parseFloat((gameheight/600).toFixed(1)),DebugMode&&console.log("ratio : "+ScreenRatio)},document.querySelectorAll(".play")[0].addEventListener("click",function(){e(a),t(canvas),o.resize(),c.sounds.background.setloop(!0),c.sounds.background.play(),s=!0}),window.addEventListener("resize",o.resize,!1),window.addEventListener("orientationchange",o.resize,!1),document.addEventListener("keydown",u.handleKeyDown,!1),document.addEventListener("keyup",u.handleKeyUp,!1),canvas.addEventListener("touchstart",u.handleStart,!1),canvas.addEventListener("touchend",u.handleEnd,!1),canvas.addEventListener("touchleave",u.handleEnd,!1),o.init()}DebugMode=!1,window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(e){window.setTimeout(e,1e3/60)}}(),game=new Game
